### ISSUE TITLE
Is this project would able to translate webassembly and dotnet IL?

### ISSUE THREAD

**Issue by Thaina** [RyanLamansky/dotnet-webassembly#2]
I'm not sure but it seem has potential to convert IL to wasm

**Comment by RyanLamansky** [comment]
Potentially, but there would be many limitations.  IL has numerous operations related to objects (`box`, `callvirt`, `castclass`, `ldfld`, `stfld` and more) that don't have direct equivalents in WebAssemby.  One would have to emulate the .NET type system and build a garbage collector to convert all features of IL.

The WebAssembly team is working on garbage collection support (see https://github.com/WebAssembly/gc ).  When this is done, it will be much easier to adapt more languages to it.  I don't think I'd attempt a .NET process until then.

Going the other direction--from WebAssembly to IL--is much easier because IL has direct equivalents for nearly all WebAssembly opcodes, and easy workarounds for those it doesn't have (incidentally, I'm working on one right now: `select`, which I'll map to a helper function).

**Comment by RyanLamansky** [comment]
Feel free to open a new issue if you have any other questions or comments 🙂
