### ISSUE TITLE
Use WASM as a vm for smart contract

### ISSUE THREAD

**Issue by wizd** [RyanLamansky/dotnet-webassembly#32]
hello,

I'm creating smart contract for our project [[link]](https://github.com/LYRA-Block-Lattice/Lyra-Core) . I wonder if your runtime could be use on blockchain? We need the vm to be fast for load/unload, parallel running, and safe. 

thanks.

**Comment by RyanLamansky** [comment]
You'd have to run your project on .NET Core 3.1 or I'd have to bring back .NET Standard 2.1 support (I removed it when Microsoft deprecated .NET Standard in favor of just making .NET Core run everywhere).

You'd probably want to block floating point opcodes since its behavior changes in subtle ways from one version of .NET to the next (I've seen slightly different results in some of the spec tests between 3.1 and 5). This wouldn't be unprecedented--the Ethereum VM doesn't support floating point.

Like the EVM, you'd probably want to assign a cost to each opcode to incentivize efficiency from the users. WebAssembly for .NET allows you to read raw WASM so you can assess the cost of running it before actually doing so. You'd probably have to use this feature inject code to account for the cost of loop iterations at run time.

WebAssembly for .NET is fast, supports loading and unloading of WASMs, parallel execution of WASMs, and has safety precautions against attack such as range checks on memory access.

Does this help?

**Comment by wizd** [comment]
much appreciated for your reply. your advice is valuable. I'll try to setup a sandbox to test the features. thank you.
