### ISSUE TITLE
Reconsider Targeting .NET Standard 2.0

### ISSUE THREAD

**Issue by JasonBock** [RyanLamansky/dotnet-webassembly#34]
I just published [`WebAssembly.Generators`](https://github.com/JasonBock/WebAssembly.Generators), which (hopefully) makes it easier to interact with a compiled .wasm file. The issue is that I needed to target `0.9.0-preview` of `WebAssembly` as that targets .NET Standard 2.0. The `1.0.0` version targets `netcoreapp3.1`, and I can't reference that from the source generator project.

I don't know how much work it would take to add .NET Standard 2.0 as another target, but if it's "minimal", then I can stay in sync with updates. If it's a lot of work, I'm curious to know what the issues are.

**Comment by RyanLamansky** [comment]
I'm definitely thinking about it.

_Pros:_
- Makes it possible to use the library on .NET Framework 4.7+.
- Satisfies the .NET Standard 2.0 restriction of Source Generators, which could reduce the pain of dealing with the external API of a given WASM.
- The API spec isn't dependent on a particular .NET SDK, should be stable forever.

_Cons:_
- .NET Standard is dead: Microsoft abandoned development of it in favor of porting .NET Core to all platforms; this was my original rationalization for dropping it.
- Supporting it could complicate long-term development since `#if`/`#else` directives will be needed to work around its limitations.

**Comment by JasonBock** [comment]
Good to hear you're thinking about it. And I agree with your pros/cons. Couple of other thoughts:

* .NET Standard **is** "dead", though I personally look at .NET 5 as being ".NET Standard 3". Immo said it best [here](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/). It's going to be around for a while, just like .NET Framework, and some of the compiler-related features still seem to "like" things being based on .NET Standard targets.
* I'm curious to know where you need directives.

**Comment by RyanLamansky** [comment]
I did a quick test and there were no issues, surprisingly. I must have been thinking about older .NET Standard versions; 2.0 seems to have harmonized things quite a bit.

I should be able to include this in the next version.

**Comment by RyanLamansky** [comment]
Done!
